import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import * as THREE from 'three';
function AvatarAccessories({ assets }) {
    return (_jsxs(_Fragment, { children: [assets.hatAssetId === 'cap' && (_jsxs("group", { position: [0, 0.82, 0], children: [_jsxs("mesh", { position: [0, 0.04, 0], children: [_jsx("coneGeometry", { args: [0.34, 0.18, 20] }), _jsx("meshStandardMaterial", { color: "#2f5eea" })] }), _jsxs("mesh", { rotation: [-Math.PI / 2, 0, 0], position: [0, -0.04, 0.18], children: [_jsx("ringGeometry", { args: [0.08, 0.24, 20] }), _jsx("meshStandardMaterial", { color: "#1d3d9d", side: THREE.DoubleSide })] })] })), assets.hatAssetId === 'crown' && (_jsxs("group", { position: [0, 0.88, 0], children: [_jsxs("mesh", { children: [_jsx("cylinderGeometry", { args: [0.24, 0.24, 0.14, 16] }), _jsx("meshStandardMaterial", { color: "#f4c63d" })] }), [0, 1, 2, 3, 4].map((i) => {
                        const angle = (Math.PI * 2 * i) / 5;
                        return (_jsxs("mesh", { position: [Math.cos(angle) * 0.2, 0.12, Math.sin(angle) * 0.2], children: [_jsx("coneGeometry", { args: [0.06, 0.12, 10] }), _jsx("meshStandardMaterial", { color: "#e5a500" })] }, i));
                    })] })), assets.shoesAssetId === 'sneakers' && (_jsxs(_Fragment, { children: [_jsxs("mesh", { position: [-0.16, -0.36, 0.16], children: [_jsx("boxGeometry", { args: [0.22, 0.12, 0.34] }), _jsx("meshStandardMaterial", { color: "#ffffff" })] }), _jsxs("mesh", { position: [0.16, -0.36, 0.16], children: [_jsx("boxGeometry", { args: [0.22, 0.12, 0.34] }), _jsx("meshStandardMaterial", { color: "#ffffff" })] })] })), assets.shoesAssetId === 'boots' && (_jsxs(_Fragment, { children: [_jsxs("mesh", { position: [-0.16, -0.33, 0.14], children: [_jsx("boxGeometry", { args: [0.24, 0.18, 0.34] }), _jsx("meshStandardMaterial", { color: "#5f4229" })] }), _jsxs("mesh", { position: [0.16, -0.33, 0.14], children: [_jsx("boxGeometry", { args: [0.24, 0.18, 0.34] }), _jsx("meshStandardMaterial", { color: "#5f4229" })] })] }))] }));
}
export function PlayerAvatar({ skinColor, assets, scale = 1.25, onClick, onPointerOver, onPointerOut }) {
    const shirtColor = new THREE.Color(skinColor).multiplyScalar(0.72).getStyle();
    return (_jsxs("group", { scale: [scale, scale, scale], onClick: onClick, onPointerOver: onPointerOver, onPointerOut: onPointerOut, children: [_jsxs("mesh", { position: [0, 0.26, 0], children: [_jsx("capsuleGeometry", { args: [0.2, 0.28, 6, 12] }), _jsx("meshStandardMaterial", { color: shirtColor })] }), _jsxs("mesh", { position: [0, 0.7, 0], children: [_jsx("sphereGeometry", { args: [0.34, 24, 24] }), _jsx("meshStandardMaterial", { color: skinColor })] }), _jsxs("mesh", { position: [-0.11, 0.12, 0], children: [_jsx("capsuleGeometry", { args: [0.07, 0.16, 4, 8] }), _jsx("meshStandardMaterial", { color: "#2b3b5b" })] }), _jsxs("mesh", { position: [0.11, 0.12, 0], children: [_jsx("capsuleGeometry", { args: [0.07, 0.16, 4, 8] }), _jsx("meshStandardMaterial", { color: "#2b3b5b" })] }), _jsxs("mesh", { position: [-0.27, 0.34, 0], rotation: [0, 0, Math.PI / 2.4], children: [_jsx("capsuleGeometry", { args: [0.055, 0.14, 4, 8] }), _jsx("meshStandardMaterial", { color: skinColor })] }), _jsxs("mesh", { position: [0.27, 0.34, 0], rotation: [0, 0, -Math.PI / 2.4], children: [_jsx("capsuleGeometry", { args: [0.055, 0.14, 4, 8] }), _jsx("meshStandardMaterial", { color: skinColor })] }), _jsxs("mesh", { position: [-0.11, 0.72, 0.29], children: [_jsx("sphereGeometry", { args: [0.03, 12, 12] }), _jsx("meshStandardMaterial", { color: "#1e2533" })] }), _jsxs("mesh", { position: [0.11, 0.72, 0.29], children: [_jsx("sphereGeometry", { args: [0.03, 12, 12] }), _jsx("meshStandardMaterial", { color: "#1e2533" })] }), _jsx(AvatarAccessories, { assets: assets })] }));
}
